name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        token: ${{ secrets.CITOKEN_SECRET }}
        submodules: true
    - name: Build
      run: |
        rustc --version || echo "no rustc"
        rustup --version
        rustup toolchain install stable 1.43.1
        rustup target list
        rustup default 1.43.1
        yarn global add wasm-pack # wasm-pack-plugin tries to install this with npm if not present, but npm needs root to install globally, so instead we install upfront with yarn
        yarn install
        yarn build
