name: CI

on:
  push:
    branches:
      - master
      - ci
    paths-ignore:
      - '**.md'  # Ignore README changes
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.CITOKEN_SECRET }}
        submodules: true
    - name: Build
      run: |
        rustc --version || echo "no rustc"
        rustup --version
        node --version
        npm --version
        npm install
        npm run build

  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.CITOKEN_SECRET }}
        submodules: true
    - name: Build
      run: |
        rustc --version || echo "no rustc"
        rustup --version
        node --version
        npm --version
        npm install
        npm run build

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.CITOKEN_SECRET }}
        submodules: true
    - name: Lint
      run: |
        npm add --global wasm-pack # wasm-pack-plugin tries to install this with npm if not present, but npm needs root to install globally, so instead we install upfront with npm
        npm install
        npm run lint
